<?php

namespace App\Filament\Resources\SettingsResource\Pages;

use App\Filament\Resources\SettingsResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditSettings extends EditRecord
{
    protected static string $resource = SettingsResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make()
            ->visible(function ($record) {
                if (in_array($record->key, config('libredesk.core_settings'))) {
                    return false;
                }

                return true;
            }),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $data = $this->setData($data);
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    public function setData($data)
    {
        $value = data_get($data, 'data.text_value');

        if (data_get($data, 'data.type') === 'color') {
            $value = data_get($data, 'data.color_value');
        }

        if (data_get($data, 'data.type') === 'options') {
            $value = data_get($data, 'data.options_value');
        }

        if (data_get($data, 'data.type') === 'image') {
            $value = data_get($data, 'data.image_value');
        }

        if (data_get($data, 'data.type') === 'select') {
            $value = data_get($data, 'data.select_value');
        }

        $data['data']['value'] = $value;
        return $data;
    }
}
