<?php

namespace App\Filament\Clusters\SettingsResource\Pages;

use App\Filament\Clusters\SettingsResource;
use Filament\Resources\Pages\CreateRecord;

class CreateSettings extends CreateRecord
{
    protected static string $resource = SettingsResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data = app(EditSettings::class)->setData($data);

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
